services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: afifa-authorization-app
        volumes:
            - .:/var/www
        depends_on:
            db:
                condition: service_healthy
        networks:
            - authorization

    db:
        image: mysql:8.0
        container_name: afifa-authorization-db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - mysqldata:/var/lib/mysql
        networks:
            - authorization
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 5

    nginx:
        image: nginx:alpine
        container_name: afifa-authorization-nginx
        ports:
            - "8383:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - authorization

    redis:
        image: redis:latest
        container_name: afifa-authorization-redis
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        ports:
            - "6393:6379"
        volumes:
            - ./redisdata:/data
        networks:
            - authorization

volumes:
    mysqldata:

networks:
    authorization:
